### ISSUE TITLE
US01 - Registration

### ISSUE THREAD

**Issue by gabibguedes** [translate-me/frontend#3]
Make a registration page with api connection. 

**Tasks:**
- [ ] Make inputs for the fields required for the registration
- [ ] Connect with the api to send the data
- [ ] Show the result  of the subscription (success/fail)

**Acceptance Criteria:**
- [ ] Use the visual identity of the project
- [ ] A new user can be registered correctly with the API connection
- [ ] The code is passing on code climate
