### ISSUE TITLE
US29, US30 - Text Editor

### ISSUE THREAD

**Issue by gabibguedes** [translate-me/frontend#4]
Make a text editor page for the translator write the translated text. This page should show the original text fragment, the information about the text and the editor to translate. It should, as well, have a "save" button, so the translator can stop his work and finish it later, and a "send" button, to sent the text to review.

**Tasks:**
- [ ] Display the information about the text on the top of the page
- [ ] Display the original text fragment on the left side of the page
- [ ] Make a text editor on the right side of the page
- [ ] Make a save button
- [ ] Make a send button

**Acceptance Criteria:**
- [ ] Use the visual identity of the project
- [ ] The user can see the original text and the editor
- [ ] The user can write a text
- [ ] The code is passing on code climate

*Obs.:* A possible way of making the editor is using DraftJs. See the following links:
- https://draftjs.org
- https://hackernoon.com/make-your-own-rich-text-editor-in-reactjs-using-draftjs-25a0b4fb05e5
