### ISSUE TITLE
Create information page

### ISSUE THREAD

**Issue by helenagoulart** [translate-me/frontend#60]
This page is on navbar and must explain who are we and what translate.me doe.

**Tasks:**
- [ ] Follow the prototype and guidestyle of colors
- [ ] Explain who are those in the project
- [ ] Explain what is it the project

**Acceptance Criteria:**
 - [ ] Follow the prototype and guidestyle of colors
