### ISSUE TITLE
Create how it works page

### ISSUE THREAD

**Issue by helenagoulart** [translate-me/frontend#62]
This page is on navbar and must explain how translate.me works.

**Tasks:**
- [ ] Follow the prototype and guidestyle of colors
- [ ] Explain all the process of being a translator and a user

**Acceptance Criteria:**
 - [ ] Follow the prototype and guidestyle of colors
